# Generated by Django 3.0.5 on 2020-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latest', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('to', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('fixed', models.BooleanField(default=False, help_text="If you set fixed to True and the error happens again, a new error will be opened. So you should set this once you THINK you've fixed it so you'll find out if you haven't.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LongRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('total_duration', models.DecimalField(decimal_places=3, help_text='In seconds.', max_digits=10)),
                ('method', models.CharField(max_length=10)),
                ('variables', models.TextField(help_text='request.POST or request.GET, depending on the method')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latest', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latest', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('to', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
