# Generated by Django 3.0.5 on 2020-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TooManyQueriesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=10)),
                ('variables', models.TextField(help_text='request.POST or request.GET, depending on the method')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latest', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('total_query_count', models.PositiveIntegerField(help_text='How many database queries happened in these requests?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
