# Generated by Django 3.0.5 on 2020-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0003_auto_20200702_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='fixedd',
            field=models.DateTimeField(blank=True, help_text="If you set fixed and the error happens again, a new error will be opened. So you should set this once you THINK you've fixed it so you'll find out if you haven't.", null=True),
        ),
    ]
