# Generated by Django 3.0.5 on 2020-07-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0004_error_fixedd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='fixed',
        ),
    ]
