# Generated by Django 3.0.5 on 2020-07-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0005_remove_error_fixed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='fixedd',
            new_name='fixed',
        ),
    ]
