# Generated by Django 3.0.5 on 2020-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0006_auto_20200704_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='longrequest',
            name='fixed',
            field=models.DateTimeField(blank=True, help_text='When, if ever, was this problem fixed?', null=True),
        ),
        migrations.AddField(
            model_name='toomanyqueriesrequest',
            name='fixed',
            field=models.DateTimeField(blank=True, help_text='When, if ever, was this problem fixed?', null=True),
        ),
    ]
