# Generated by Django 3.0.5 on 2020-07-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0008_auto_20200710_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='fixed',
            field=models.DateTimeField(blank=True, help_text='When, if ever, was this problem fixed?', null=True),
        ),
    ]
