# Generated by Django 3.0.5 on 2020-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djavError', '0009_auto_20200714_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longrequest',
            name='variables',
            field=models.TextField(blank=True, help_text='request.POST or request.GET, depending on the method', null=True),
        ),
        migrations.AlterField(
            model_name='toomanyqueriesrequest',
            name='variables',
            field=models.TextField(blank=True, help_text='request.POST or request.GET, depending on the method', null=True),
        ),
    ]
